sw360/capycli

- Readme.md
Now that CaPyCli is Open Source, we should clearly state what this is about to not mislead users about what kind of clearing we support. :)
> docs: mention SW360 and license clearing in title

- capycli/project/create_project.py
The change fixes the type error reported in #20. Tested on python 3.10.4.
> fix: typeError on project creation when no SW360 ID given

- capycli/common/capycli_bom_support.py
During usage noticed an inconsistency in the external reference URL of the Siemens standard bom.
> fix: external reference to Siemens standard bom

- capycli/project/get_license_info.py
- tests/test_get_license_info.py
As preparation for #24, I tried to understand exact usage of "project getlicenseinfo" and was a bit confused about the idea of "-o", so I tried to make it clearer. Also, the error message when not specifying "-o" confused me, so I removed it completely and made it optional instead. :)
> Project getlicenseinfo help and option improvement

- ChangeLog.md
- capycli/common/capycli_bom_support.py
- capycli/project/create_bom.py
- tests/test_create_bom.py
This PR fixes "project CreateBom" to store the following data to written BOM:
- feat: SW360 project name, version and description are now added to metadata/component
- fix: purls from linked releases are taken over from SW360, due to a bug capycli always re-created them guessing from name, version and language
- fix: source and binary urls are taken over from SW360, due to a bug they got lost
> `project createbom` improvements: add SW360 project metadata and fix components' purls and source/binary urls

- capycli/bom/findsources.py
- capycli/common/capycli_bom_support.py
- tests/fixtures/sbom_for_find_sources.json
- tests/test_find_sources.py
Command "bom findsources" is extended to cover external references of type "distribution" and accepts a broader format variety of GitHub URLs (e.g., starting with git+https://, or git://, or missing URL altogether but having a valid GitHub project name format).
Closes #23
> feat: broaden the scope of the find sources command

- ChangeLog.md
- capycli/project/create_bom.py
- tests/test_base.py
- tests/test_create_bom.py
These got lost because they were added internally using a wrong legacy attribute.
This will be changed again when refactoring createbom as suggested in #30, but I thought it might be worth having a working version  first as reference.
> fix(project CreateBom): include SW360 source attachments and repository url

- capycli/bom/download_sources.py
- capycli/common/capycli_bom_support.py
- capycli/common/script_base.py
- capycli/project/create_bom.py
- capycli/project/show_ecc.py
- tests/test_base.py
- tests/test_bom_downloadsources.py
- tests/test_logging.py
During development for #33, I stumbled over some methods I wanted to improve and decided to restructure some others for better re-use or better testability.
I think these commits are ready to be merged if you agree, so we could reduce the patch queue in #33.
> Rework some project and bom methods

- ChangeLog.md
- capycli/project/create_bom.py
- tests/test_create_bom.py
When creating an SBOM from a SW360 project, add all to the SBOM separated by spaces, but warn the user to manually fix the SBOM.
This is still a draft as it lacks a testcase.
Fixes #36
> fix(project CreateBom): decode multiple purls and warn user

- ChangeLog.md
- capycli/project/create_bom.py
- tests/test_base.py
- tests/test_create_bom.py
Note that his is a PR on top of #37, so it includes the change from #37.
Fixes #39 by adding the necessary infrastructure for pytest-based test classes and refactoring the "project createbom" testcases to use it.
This shows the pytest assert syntax and how to capture stdout with pytest using the "capsys" fixture.
> Issue39 first pytest file

- capycli/main/options.py
The command was listed in "capycli project --help", but not in "capycli --help"
> fix(options): "project CreateBom" missing in cmd summary

- capycli/bom/findsources.py
- capycli/common/script_base.py
- capycli/main/options.py
- poetry.lock
- pyproject.toml
- tests/test_base.py
- tests/test_find_sources.py
- tests/test_get_dependencies_python.py
Conduct source URL discovery using sw360 lookup, perform extensive GitLab deep search, and adapt search strategy based on diverse programming languages.
> Improve findsources functionality

- capycli/bom/legacy.py
When we convert BOM from legacy to capycli [ capycli bom convert  -i <input.json> -if legacy -o <output.json> -of capycli ] "SourceUrl" from legacy BOM is getting converted to "source archive (local copy)" in capycli BOM.
What should be the actual conversion?
It should be converted to "source archive (download location)"
> fix: legacy to capycli BOM convert fix for sourceUrl

- capycli/bom/findsources.py
If the component is a Debian package, capycli will bypass the steps to locate the source URL, as GitHub URLs are not valid for Debian components.
> fix: skip debian components to find github urls

- capycli/common/capycli_bom_support.py
This PR is to address [this](https://github.com/sw360/capycli/issues/70) issue.
@gernot-h Please have a look.
> fix: convert invalid uri regex

- capycli/bom/map_bom.py
- capycli/common/capycli_bom_support.py
- tests/test_bom_map2.py
As discussed in #71, the previous fix hard-replaced certain special characters by ":" in all external references, so this reverts #71.
Instead, I think we need to percent-encode filenames.
> Finally fix #70 with correct percent-encoding

- capycli/bom/check_granularity.py
- tests/test_check_granularity.py
Urls coming from granularity file are repository urls and not source code download urls. Hence making changes in check_granularity.py file and related testcase.
> fix: urls coming from granularity file are repository urls and not source code download urls

- capycli/bom/findsources.py
As we skip source url checks for debian components, the if condition is updated to add checks for bom_ref and purl
> fix: bom_ref is not set always hence adding purl also for the checks

- capycli/bom/filter_bom.py
- capycli/common/capycli_bom_support.py
- tests/test_bom_filter.py
- tests/test_bom_map2.py
- tests/test_get_dependencies_javascript.py
Current CaPyCli code set the URL to a string internally which doesn't harm when the SBOM is immediately written to a file. If you however want to manipulate the SBOM internally, it can lead to problems as discussed in #79.
> Use XsUri when updating an existing external reference

- capycli/bom/create_components.py
- tests/test_bom_create_releases.py
This pull request addresses 1st and 2nd point of the https://github.com/sw360/capycli/issues/100 issue.
1. It reverts the override of the source code SW360 URL when the capycli recognises the source code download URL ending with .zip, .tgz, .tar.gz, .tar.
2. Prevention of the .git file upload is now done only for the SOURCE and SOURCE_SELF filetype (with added tests).
> fix: override logic of sw360 urls and rework prevention of .git upload

- tests/test_bom_create_releases.py
This is a follow-up to #92 and adapts the URL in the test to the hard-coded pattern introduced there, to assure that we don't overwrite existing URLs in SW360 as discussed in #100.
> test(bom createreleases): assure behaviour on diverging source URLs

- ChangeLog.md
- capycli/bom/map_bom.py
- capycli/common/comparable_version.py
- tests/test_bom_map2.py
As described in #117, invalid SW360 version numbers (which can't be parsed by ComparableVersion) lead to an exception caught quite late, leading to "bom map" forgetting a component in the output BOM. 
This PR makes the exception being caught in time, but in my eyes doesn't completely fix #117 as other exceptions in the long code base of map_bom_* can lead to the same problem, so we should still discuss error handling in #117.
> fix bug triggering #117, leading to loosing components during "bom map"

- capycli/__init__.py
CaPyCli expects that it's either installed from a stable package or run from a Git clone. If you install it from a branch, e.g. using Poetry, it will crash as it can find neither package metadata nor pyproject.toml.
Fixes #132
> fix: don't crash when CaPyCli installed from branch

- Readme_BOM.md
- Readme_Mapping.md
- capycli/bom/map_bom.py
- capycli/common/purl_service.py
- capycli/common/purl_store.py
- tests/test_bom_map2.py
- tests/test_purl_service.py
- tests/test_purl_store.py
This change shall have no visible effect to the user – BOM mapping shall behave as before. But it prepares the lower layers for the changes discussed in #123 and #139:
Don't filter out duplicate versions or components when building up purl cache. Instead, they are now filtered in the PurlService methods search_release_by_external_id and search_component_by_external_id. This change also aligns both methods to return None if nothing is found.
Additionally, the PurlService now offers new methods search_release*s*_by_external_id and search_component*s*_by_external_id which return all candidates including duplicates.
> feat(purl_store): allow duplicate purls in cache

- ChangeLog.md
- capycli/bom/map_bom.py
- tests/test_bom_map2.py
As described in #118, this fixes rare cases where `bom map` added good and worse matches to the output BOM for --nocache mode.
This first adds test cases for some missing cases to reduce the risk we break things on refactoring, then moves the existing code to a central method and finally improves the match handling there.
> Fix #118 mixed name and full matches

- ChangeLog.md
- capycli/common/capycli_bom_support.py
- capycli/project/create_bom.py
- capycli/project/create_project.py
- tests/fixtures/sbom_for_create_project.json
- tests/test_base.py
- tests/test_create_bom.py
- tests/test_create_project.py
- tests/test_show_project.py
This changes the release state handling during "project update". Instead of storing project release states from SW360 and restoring it release by release at the end, we pass on full release data to REST API endpoint for updating linked releases.
As an SBOM has to be provided during "project update" or "project create --copy_from" anyways, we take the release states stored in the SBOM instead of keeping the state in SW360.
Note that this requires also the change from https://github.com/sw360/sw360python/pull/41 for correct "project update" support. 
Fixes #121
> avoid "Restoring original project mainline states" during "project update"

- capycli/project/create_project.py
Resetting the "project_info" has an undesired side-effect: doesn't allow the patch of the SW360 project for fields like (example): "linkedProjects", "moderators".
> Revert breaking change (reset of project_info)

- ChangeLog.md
- Readme_Mapping.md
- capycli/bom/create_components.py
- capycli/bom/map_bom.py
- capycli/common/capycli_bom_support.py
- capycli/common/map_result.py
- capycli/common/purl_service.py
- capycli/common/purl_store.py
- capycli/common/purl_utils.py
- capycli/main/options.py
- tests/test_base.py
- tests/test_bom_map2.py
- tests/test_purl_service.py
- tests/test_purl_store.py
- tests/test_purl_utils.py
Contains following changes/features:
* always search through all releases and include all best matches, don't abort on first good match -> implements #150
* return multiple releases with matching PURL -> implements #139
* consider PURL qualifiers during mapping if there's a full qualifier match -> implements #139
Fixes #139 
Fixes #150
> PURL qualifier-based search
